// import mongoose from "mongoose";

// const serviceSchema = new mongoose.Schema(
//   {
//     sector: String,
//     service: String,
//     resource: String,
//     peopleServed: Number,
//     employee: String,
//     date: Date,
//     remark: String,
//   },
//   { _id: false },
// );

// const reportSchema = new mongoose.Schema(
//   {
//     coordinatorName: String,
//     coordinatorDate: Date,
//     signature: String,

//     services: [serviceSchema],

//     createdBy: {
//       type: mongoose.Schema.Types.ObjectId,
//       ref: "User",
//     },

//     // ✅ ADD THIS
//     fileName: {
//       type: String,
//       required: true,
//     },
//   },
//   { timestamps: true },
// );

// export default mongoose.model("Report", reportSchema);

import mongoose from "mongoose";

const serviceSchema = new mongoose.Schema(
  {
    sector: String,
    service: String,
    resource: String,
    peopleServed: Number,
    employee: String,
    date: Date,
    remark: String,
  },
  { _id: false },
);

const reportSchema = new mongoose.Schema(
  {
    coordinatorName: String,
    coordinatorDate: Date,
    signature: String,
    services: [serviceSchema],
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    // File from form data (generated by backend)
    generatedFileName: {
      type: String,
    },
    // File uploaded by user
    uploadedFileName: {
      type: String,
    },
  },
  { timestamps: true },
);

export default mongoose.model("Report", reportSchema);